- .husky/pre-commit
- .vscode/settings.json
- package.json
- packages/core/package.json
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casper-dash.ts
- packages/core/src/connectors/casper-signer.ts
- packages/core/src/errors/ConnectorNotFoundError.ts
- packages/core/src/errors/WindowNotFound.ts
- packages/core/src/errors/index.ts
- packages/core/src/types/global.d.ts
- pnpm-lock.yaml
- tsconfig.json
> Feat: Connectors

- examples/example-react/src/App.tsx
- packages/core/src/actions/account/getActivePublicKey.ts
- packages/core/src/connectors/casper-dash.ts
- packages/core/src/connectors/casper-signer.ts
- packages/core/src/utils/client.ts
- Window events to trigger account changed
> Feat: Window events to trigger account changed

- examples/example-react/src/App.tsx
- examples/example-react/src/component/CasperDashButton.tsx
- examples/example-react/src/component/CasperSignerButton.tsx
- packages/core/src/actions/account/connect.ts
- packages/core/src/actions/signing/index.ts
- packages/core/src/actions/signing/sign.ts
- packages/core/src/actions/signing/signMessage.ts
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casper-dash.ts
- packages/core/src/connectors/casper-signer.ts
- packages/core/src/index.ts
- packages/react/src/enums/index.ts
- packages/react/src/enums/mutationKeys.ts
- packages/react/src/enums/queryKeys.ts
- packages/react/src/hooks/index.ts
- packages/react/src/hooks/useAccount.ts
- packages/react/src/hooks/useConnect.ts
- packages/react/src/hooks/useDisconnect.ts
- packages/react/src/hooks/useSign.ts
- packages/react/src/hooks/useSignMessage.ts
- packages/react/src/index.ts
- pnpm-workspace.yaml
- Add new useSign and useSignMessage hooks
- Add new useDisconnect hook
- Refactor useConnect hook
> Feat: useSign and useSignMessage

- packages/core/package.json
- packages/core/src/actions/account/getAccount.ts
- packages/core/src/index.ts
- packages/core/src/utils/deepEqual.ts
- packages/core/src/utils/index.ts
- packages/react/package.json
- packages/react/src/hooks/useAccount.ts
- packages/react/src/provider.ts
- pnpm-lock.yaml
- Refactor useAccount hooks
- Add useClient with provider
> Feat: useClient with provider

- .eslintrc
- .gitignore
- examples/example-react/vite.config.ts
- package.json
- packages/core/src/actions/account/connect.ts
- packages/core/src/actions/account/disconnect.test.ts
- packages/core/src/actions/account/disconnect.ts
- packages/core/src/actions/account/getAccount.test.ts
- packages/core/src/actions/account/getAccount.ts
- packages/core/src/actions/account/getActivePublicKey.test.ts
- packages/core/src/actions/account/getActivePublicKey.ts
- packages/core/src/actions/account/isConnected.test.ts
- packages/core/src/actions/account/isConnected.ts
- packages/core/src/enums/status.ts
- packages/core/src/utils/client.ts
- packages/react/src/hooks/useAccount.ts
- pnpm-lock.yaml
- vitest.config.ts
- Unit tests:
1. getAccount
2. getActivePublicKey
3. isConnected
4. disconnect
> Test: Core functions

- packages/core/src/actions/account/connect.test.ts
- packages/core/src/actions/account/connect.ts
- Unit test for connecting function
-   [x] I removed all comments or unnecessary code.
-   [ ] Provide the screenshots due to UI changes or bug fixed
> Test(core): Connect function

- .eslintrc
- examples/example-react/package.json
- examples/example-react/src/App.css
- examples/example-react/src/App.tsx
- examples/example-react/src/component/FormSigner.tsx
- examples/example-react/src/index.css
- examples/example-react/src/utils/valueBuilder.ts
- packages/core/package.json
- packages/core/src/actions/signing/sign.ts
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casper-dash.ts
- packages/core/src/connectors/casper-signer.ts
- packages/core/src/types/casperLabsHelper.d.ts
- packages/react/src/hooks/useSign.ts
- packages/react/src/hooks/useSignMessage.ts
- pnpm-lock.yaml
- Refactor sign and signMessage function
- Sign example with react
> Feat: Sign example with React

- .eslintrc
- examples/example-react/package.json
- examples/example-react/src/component/CasperDashButton.tsx
- examples/example-react/src/main.tsx
- packages/core/src/actions/account/disconnect.test.ts
- packages/core/src/actions/account/getAccount.test.ts
- packages/core/src/actions/account/getActivePublicKey.test.ts
- packages/core/src/actions/account/isConnected.test.ts
- packages/core/src/actions/account/watchAccount.test.ts
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casperDash.test.ts
- packages/core/src/connectors/casperDash.ts
- packages/core/src/connectors/casperSigner.ts
- packages/core/src/connectors/index.ts
- pnpm-lock.yaml
- Unit test for:
1. CasperDashConnector
2. watchAccount function
> Test: casperDash connector and watchAccount

- packages/core/src/connectors/casperSigner.test.ts
- packages/core/src/connectors/casperSigner.ts
> Test: CasperSigner connector

- packages/core/src/actions/signing/sign.test.ts
- packages/core/src/actions/signing/sign.ts
- packages/core/src/actions/signing/signMessage.test.ts
- packages/core/src/actions/signing/signMessage.ts
- Unit test for sign and signMessage
> Test: sign and signMessage

- packages/core/src/connectors/casperSigner.test.ts
- packages/core/src/errors/WindowNotFound.ts
- packages/core/src/errors/index.ts
- packages/core/src/utils/client.test.ts
- packages/core/src/utils/client.ts
- packages/core/src/utils/deepEqual.test.ts
> Test(core): Utils with client and deepEqual

- package.json
- packages/core/src/actions/account/connect.ts
- packages/core/src/index.ts
- packages/react/package.json
- packages/react/src/client.ts
- packages/react/src/hooks/useConnect.test.ts
- packages/react/src/hooks/useDisconnect.test.ts
- packages/react/src/provider.ts
- packages/react/test/index.ts
- packages/react/test/reactUtil.tsx
- pnpm-lock.yaml
- Unit test for react hooks: useConnect and useDisconnect
> Test(react): useConnect and useDisconnect

- packages/react/src/hooks/useSign.test.ts
- packages/react/src/hooks/useSign.ts
- packages/react/src/hooks/useSignMessage.test.ts
- packages/react/src/hooks/useSignMessage.ts
- Unit test for react hooks: useSign and useSignMessage
> Test(react): useSign and useSignMessage

- examples/example-react/src/main.tsx
- packages/core/src/actions/account/disconnect.ts
- packages/core/src/utils/client.test.ts
- packages/core/src/utils/client.ts
- packages/react/src/hooks/useAccount.ts
> Feat(core): Auto connect wallet

- docs/tsconfig.json
- package.json
- Add CLI to run dev and build docs
> Docs: Add CLI to run dev and build

- README.md
> Docs: Update readme features

- packages/react/src/hooks/useAccount.test.ts
> Test: useAccount

- packages/core/src/connectors/casperDash.test.ts
- packages/core/src/connectors/casperDash.ts
- packages/core/src/types/global.d.ts
- Change global name casperDash
> Refactor: Rename casperDash global

- README.md
- packages/react/README.md
> Docs: import wallet on readme

- .github/workflows/publish-docs.yml
- .gitignore
- docs/pages/index.mdx
- docs/theme.config.tsx
> Configure Deploy Doc to S3

- examples/example-react/src/App.tsx
- packages/core/src/utils/deepEqual.ts
- packages/react/src/hooks/index.ts
- packages/react/src/hooks/useAccount.ts
Root cause:
- onConnect not working when the user connect to the wallet
Solution:
- Check prevAccount with currentAccount and status is connected
> Fix: onConnect event with useAccount

- packages/core/src/actions/account/connect.ts
- packages/core/src/actions/account/disconnect.ts
- packages/core/src/actions/account/getAccount.ts
- packages/core/src/actions/account/getActivePublicKey.ts
- packages/core/src/actions/account/isConnected.ts
- packages/core/src/actions/account/watchAccount.ts
- packages/core/src/actions/signing/sign.ts
- packages/core/src/actions/signing/signMessage.ts
- packages/core/src/connectors/casperDash.ts
- packages/core/src/connectors/casperSigner.ts
- packages/core/src/utils/client.ts
- packages/react/src/provider.ts
> Add comments

- packages/core/src/actions/account/disconnect.ts
- packages/core/src/actions/account/watchAccount.ts
- packages/core/src/connectors/casperDash.test.ts
- packages/core/src/connectors/casperDash.ts
- packages/core/src/connectors/casperSigner.ts
- packages/core/src/types/deploy.d.ts
- packages/core/src/utils/client.ts
- packages/core/src/utils/deepEqual.ts
> Chore: Remove space for eslint

- examples/example-react/src/App.tsx
- package.json
- packages/core/package.json
- packages/core/src/actions/account/connect.test.ts
- packages/core/src/actions/account/connect.ts
- packages/core/src/actions/account/watchAccount.ts
- packages/core/src/utils/deepEqual.ts
- packages/react/package.json
- packages/react/src/hooks/index.ts
- packages/react/src/hooks/useAccount.ts
- packages/react/src/hooks/useConnect.ts
- Fix: onConnect event with useAccount
- Update code comment
> Release: 0.0.2

- examples/example-react/src/main.tsx
- packages/core/src/actions/account/connect.test.ts
- packages/core/src/actions/account/connect.ts
- packages/core/src/actions/account/disconnect.ts
- packages/core/src/actions/signing/sign.ts
- packages/core/src/actions/signing/signMessage.ts
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casperDash.ts
- packages/core/src/connectors/casperSigner.test.ts
- packages/core/src/connectors/casperSigner.ts
- packages/core/src/enums/status.ts
- packages/core/src/utils/client.ts
- packages/core/src/utils/storage.ts
> Fix: autoConnect not work with some projects

- examples/example-react/src/main.tsx
- package.json
- packages/core/package.json
- packages/core/src/actions/account/connect.test.ts
- packages/core/src/actions/account/connect.ts
- packages/core/src/actions/account/disconnect.ts
- packages/core/src/actions/signing/sign.ts
- packages/core/src/actions/signing/signMessage.ts
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casperDash.ts
- packages/core/src/connectors/casperSigner.test.ts
- packages/core/src/connectors/casperSigner.ts
- packages/core/src/enums/status.ts
- packages/core/src/utils/client.ts
- packages/core/src/utils/storage.ts
- packages/react/package.json
- Improve autoConnect with Casper signer locked
- Improve autoConnect if Casper Signer and CasperDash run before
> Release: 0.0.3

- examples/example-react/package.json
- examples/example-react/src/App.tsx
- examples/example-react/src/component/CasperWalletButton.tsx
- examples/example-react/src/component/FormSigner.tsx
- examples/example-react/src/main.tsx
- examples/example-react/vite.config.ts
- packages/core/package.json
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casperDash.ts
- packages/core/src/connectors/casperWallet.ts
- packages/core/src/connectors/index.ts
- packages/core/src/types/casperLabsHelper.d.ts
- packages/core/src/types/casperWalletProvider.d.ts
- packages/core/src/types/global.d.ts
- packages/core/src/utils/client.ts
- packages/core/src/utils/parser.ts
- packages/react/src/client.ts
- pnpm-lock.yaml
> Feat: Casper Wallet connector

- packages/core/src/connectors/casperWallet.test.ts
- pnpm-lock.yaml
- Unit test for casper wallet connector
> Test: Casper wallet connector

- examples/example-react/package.json
- examples/example-react/src/App.tsx
- examples/example-react/src/component/CasperWalletButton.tsx
- examples/example-react/src/component/FormSigner.tsx
- examples/example-react/src/main.tsx
- examples/example-react/vite.config.ts
- packages/core/package.json
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casperDash.ts
- packages/core/src/connectors/casperWallet.test.ts
- packages/core/src/connectors/casperWallet.ts
- packages/core/src/connectors/index.ts
- packages/core/src/types/casperLabsHelper.d.ts
- packages/core/src/types/casperWalletProvider.d.ts
- packages/core/src/types/global.d.ts
- packages/core/src/utils/client.ts
- packages/core/src/utils/parser.ts
- packages/react/package.json
- packages/react/src/client.ts
- pnpm-lock.yaml
- Integrate with Casper Wallet
> Release: 0.0.4

- packages/core/package.json
- packages/core/src/connectors/casperWallet.ts
- packages/core/src/utils/client.ts
- packages/react/package.json
**Bug Fixes:**
- Fixed the error in NextJs when loading our library on the server side with the window variable. (Commit: 2364435cdcb6b13834c05754b61928f4d6748af6) #55
**Improvements:**
- Imported CommonJS default exports as named exports to address the inability to load ES modules. (Commit: https://github.com/CasperDash/useWallet/pull/54/commits/82baccac550ab5ea3ff3613357312e62deeccace)
> Release: 0.0.5

- .github/workflows/dev.yml
- examples/example-react/src/App.tsx
- examples/example-react/src/component/CasperDashWebButton.tsx
- examples/example-react/src/component/FormSigner.tsx
- examples/example-react/src/component/FormSignerMessage.tsx
- examples/example-react/src/utils/valueBuilder.ts
- package.json
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casperDashWeb.ts
- packages/core/src/connectors/casperWallet.ts
- packages/core/src/connectors/index.ts
- packages/core/src/enums/eventKeys.ts
- packages/core/src/enums/postMessageMethod.ts
- packages/core/src/errors/ProviderUrlDoesNotExistError.ts
- packages/core/src/errors/RejectedSignDeployError.ts
- packages/core/src/errors/RejectedSignMessageError.ts
- packages/core/src/errors/index.ts
- packages/react/src/client.ts
- tsconfig.json
- Support CasperDash web dApp connector
> Feat: Casper Web wallet connector

- .github/workflows/dev.yml
- examples/example-react/src/App.tsx
- examples/example-react/src/component/CasperDashWebButton.tsx
- examples/example-react/src/component/FormSigner.tsx
- examples/example-react/src/component/FormSignerMessage.tsx
- examples/example-react/src/utils/valueBuilder.ts
- package.json
- packages/core/package.json
- packages/core/src/connectors/base.ts
- packages/core/src/connectors/casperDashWeb.ts
- packages/core/src/connectors/casperWallet.ts
- packages/core/src/connectors/index.ts
- packages/core/src/enums/eventKeys.ts
- packages/core/src/enums/postMessageMethod.ts
- packages/core/src/errors/ProviderUrlDoesNotExistError.ts
- packages/core/src/errors/RejectedSignDeployError.ts
- packages/core/src/errors/RejectedSignMessageError.ts
- packages/core/src/errors/index.ts
- packages/react/package.json
- packages/react/src/client.ts
- [Feat: Casper Web wallet connector ](https://github.com/CasperDash/useWallet/commit/bbd12ee30d0286acd0be604abb7ab2351acd7ff9)
> Release: 0.0.6

- README.md
- docs/pages/index.mdx
- docs/pages/react/getting-started.mdx
- docs/pages/react/hooks/useConnect.mdx
- packages/react/README.md
> Chore: Wrong typo close tag

- packages/core/src/connectors/base.ts
- Add options param on sign and sign message function
> Refactor: Add options param on sign and sign message function

- examples/example-react/src/App.tsx
- packages/core/src/actions/account/getActivePublicKey.ts
- packages/core/src/actions/account/watchAccount.ts
- packages/react/src/hooks/useAccount.ts
> Refactor: useAccount with on error params

- examples/example-react/src/App.tsx
- packages/core/package.json
- packages/core/src/actions/account/getAccount.ts
- packages/core/src/actions/account/watchAccount.ts
- packages/core/src/utils/client.ts
- packages/react/package.json
- packages/react/src/hooks/useAccount.ts
- packages/react/src/index.ts
-`onChange` account event with isConnected status from `useAccount` hook
> Patch: 0.0.7

- packages/core/package.json
- packages/core/src/connectors/casperLedger.ts
- packages/react/package.json
- Support esModule converted for zonax ledger
> Patch: 0.1.1

- examples/example-react/src/App.tsx
- packages/core/package.json
- packages/core/src/connectors/casperLedger.ts
- packages/react/package.json
- packages/react/src/hooks/useAccount.ts
> Patch: 0.1.3

- examples/example-react/src/component/SelectLedgerAccount.tsx
- packages/react/src/hooks/useFetchLedgerAccounts.ts
> Feat: Infinities scroll for fetch ledger

- docs/pages/react/hooks/useDisconnect.mdx
- docs/pages/react/hooks/useSign.mdx
- docs/pages/react/hooks/useSignMessage.mdx
- packages/react/README.md
Related: https://github.com/CasperDash/useWallet/issues/81
> Docs: Fix error typo

- packages/core/package.json
- packages/core/src/utils/client.ts
- packages/ledger/package.json
- packages/react/package.json
> HotFix: 1.0.2 Catch ledger error when auto-connect
